options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/food-safety', '.']
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  # Run the build script
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'food-safety', '--image', 'gcr.io/$PROJECT_ID/food-safety', '--region', 'europe-west1', '--allow-unauthenticated']
